### ISSUE TITLE
Non forniamo la soluzione agli studenti

### ISSUE THREAD

**Issue by korsmakolnikov** [CodeGardenRome/lambda-garden-due#2]
Non forniamo le nostre soluzioni agli studenti. Mettiamo le soluzioni su lambda-garden-due-solutions

Diamo agli studenti un repo con 
1. le slide
2. una serie di cartelle per linguaggio con lo scaffolding dell'applicazione basica e un solo test, il controllo della prima linea 

All'inizio del workshop chiediamo a tutti gli studenti di **creare un branch col loro nome e cognome**

Alla fine del workshop chiediamo a tutti gli studenti di **pushare il loro branch**

**Comment by ivanopagano** [comment]
farei fare un fork del repo e li farei lavorare li', qual'e' l'utilita' di tenere tutte le soluzioni su questo repo?

**Comment by ivanopagano** [comment]
A ben pensarci, per poter iniziare senza perdere tempo a lavorare, potremmo fornire un link nella pagina del meetup.

All'interno di ogni sotto cartella, per ciascun linguaggio, fornire lo scheletro e spiegare come installare i tool necessari (node, stack, sbt, leiningen, gradle, ...)

Specificando come verificare che tutto sia a posto (e.g. esegui gradle build) possiamo sperare che le persone vengano all'incontro con l'ambiente gia' pronto a lavorare...

Magari suggeriamo anche di caricare il progetto nel proprio editor/ide favorito, prima di venire, in modo da ridurre i tempi morti.

**Comment by korsmakolnikov** [comment]
Quindi: 
```
cartella_linguaggio/
     README.md -> istruzioni per iniziare, istallare l'ambiente, verifiche per il funzionamento, ecc
     ... -> scaffold del progetto
```

**Comment by korsmakolnikov** [comment]
> farei fare un fork del repo e li farei lavorare li', qual'e' l'utilita' di tenere tutte le soluzioni su questo repo?

Le soluzioni nostre o quelle degli lambders? Per me non è proprio utile presentare soluzioni da parte nostra. È un workshop, si lavora insieme, non è una scuola in definitiva anche se pure io li chiamo studenti a volte. 
Per le loro soluzioni è differente. Possono forcare un loro branch e pushare sul repo, confrontarsi, sfruttare github per discuterne, continuare a lavorarci oltre l'evento.

**Comment by ivanopagano** [comment]
@korsmakolnikov intendo per le loro soluzioni, tu suggerivi di farli lavorare su `branch` dedicati e poi fare push.

Quindi finirebbe tutto su questo repository. E' utile avere qui tutte le soluzioni sviluppate?

Altrimenti ognuno fa il suo fork, e lavora da li', e questo repo rimane pulito...

Non so cos'e' meglio

**Comment by korsmakolnikov** [comment]
> E' utile avere qui tutte le soluzioni sviluppate?

Io dicevo che ognuno di loro potrebbe forcare su un branch col suo nome, da là potrebbero usare github per confrontarsi e anche per sottoporre le soluzioni pushando. È un idea tutto qua.

**Comment by ivanopagano** [comment]
Io direi che questa e' risolta
